In [4]:
import pandas as pd
import re
import numpy as np

In [5]:
dfforb = pd.read_csv('../../../Ironhack-Module-1-Project-Mecaho/data/raw/dfforb1.csv')
dfpop = pd.read_csv('../../../Ironhack-Module-1-Project-Mecaho/data/raw/dfpop1.csv')

In [6]:
dffull = dfforb.merge(dfpop, how='left', left_on='country', right_on='country')
dffull.to_csv('../../../Ironhack-Module-1-Project-Mecaho/data/raw/dffull.csv',sep=',', index = False)
dffull

,id,name,position,Unnamed: 0,id.1,lastName,age,Unnamed: 0.1,gender,country,...,Source_x,worth,worthChange,realTimeWorth,realTimePosition,rank_pop,population,weight_wpopulation,date,Source_y
0,5948,jeff BEzos,1.0,52,5948,beZOS,54 years old,52,None,World,...,Technology ==> Amazon,112.0 BUSD,0.0 millions USD,NaN,1,–,"7,758,960,000",100%,4 Jan 2020,UN projection[200]
1,7342,BILL GAtes,2.0,53,7342,GATEs,62 years old,53,M,World,...,Technology ==> Microsoft,90.0 BUSD,-0.001 millions USD,NaN,2,–,"7,758,960,000",100%,4 Jan 2020,UN projection[200]
2,5447,warren BUFFETT,3.0,54,5447,bufFETT,87 years old,54,None,United States,...,Finance and Investments ==> Berkshire Hathaway,84.0 BUSD,-0.002 millions USD,NaN,3,3,"330,529,481",4.26%,4 Jan 2020,National population clock
3,4420,bernARD ARNAULt,4.0,55,4420,aRNAULT,69 years old,55,M,France,...,Fashion & Retail ==> LVMH,72.0 BUSD,0.0 millions USD,NaN,4,20,"67,081,000",0.865%,1 Nov 2019,Monthly National estimate[20]
4,4071,mark ZUCKerberg,5.0,56,4071,zuckERBERg,1985,56,M,World,...,Technology ==> Facebook,71.0 BUSD,0.0 millions USD,NaN,5,–,"7,758,960,000",100%,4 Jan 2020,UN projection[200]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2203,3917,ZHAO XIAOQIang,2204.0,2255,3917,zhAO,51 years old,2255,M,China,...,"Fashion & Retail ==> fashion, entertainment",1.0 BUSD,0.0 millions USD,NaN,2134,1,"1,400,737,880",18.1%,4 Jan 2020,National population clock
2204,3721,zhou liANgzhang,2205.0,2256,3721,zhOU,55 years old,2256,M,World,...,Manufacturing ==> electrical equipment,1.0 BUSD,nan millions USD,NaN,2134,–,"7,758,960,000",100%,4 Jan 2020,UN projection[200]
2205,6132,zhU XINGMING,2206.0,2257,6132,zHU,51 years old,2257,None,World,...,Manufacturing ==> electrical equipment,1.0 BUSD,0.0 millions USD,NaN,1856,–,"7,758,960,000",100%,4 Jan 2020,UN projection[200]
2206,7866,zhuo JUN,2207.0,2258,7866,zHUO,52 years old,2258,F,World,...,Manufacturing ==> printed circuit boards,1.0 BUSD,0.0 millions USD,NaN,1978,–,"7,758,960,000",100%,4 Jan 2020,UN projection[200]
2207,2968,olGUN ZOrlu,2208.0,2259,2968,zORLU,54 years old,2259,M,World,...,Diversified ==> diversified,1.0 BUSD,nan millions USD,NaN,1978,–,"7,758,960,000",100%,4 Jan 2020,UN projection[200]